server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.jks
    key-store-password: 123456
    key-alias: server
    trust-store: classpath:server-truststore.jks
    trust-store-password: 123456
#    client-auth: need  # ??????? mTLS