version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: "gitlab"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    networks:
      gitlab-network:
        aliases:
          - gitlab.local

  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    depends_on:
      - gitlab
    volumes:
      - ./runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-network
    extra_hosts:
      - "gitlab:host-gateway"


  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - gitlab-network
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    command: serve

networks:
  gitlab-network:
    name: gitlab-network
    driver: bridge
    external: true